# ==============================================================================
# ConfigMap patch — LOCAL (sobrescreve valores do base/configmap.yaml)
# ==============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: techchallenge
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "TechChallenge"
  Jwt__Audience: "techchallenge.com.br"
  DOTNET_USE_POLLING_FILE_WATCHER: "true" # Hot Reload em produção não é recomendado, mas aqui ajuda muito no desenvolvimento
