# ==============================================================================
# ConfigMap patch — AWS (sobrescreve valores do base/configmap.yaml)
# ==============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: techchallenge
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "TechChallenge"
  Jwt__Audience: "techchallenge.com.br"
  OTEL_SERVICE_NAME: "techchallenge-api"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://datadog-agent.datadog.svc.cluster.local:4318"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=techchallenge,deployment.environment=production"
