apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: techchallenge-api
  namespace: techchallenge
  labels:
    app.kubernetes.io/part-of: techchallenge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
