// <auto-generated />
using System;
using Fiap.TechChallenge.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiap.TechChallenge.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503033134_AddTempoEstimadoServico")]
    partial class AddTempoEstimadoServico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdPecaInsumo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_peca_insumo");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdPecaInsumo")
                        .IsUnique();

                    b.ToTable("estoque", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.ItemPecaInsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdOrdemServico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ordem_servico");

                    b.Property<Guid>("IdPecaInsumo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_peca_insumo");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdemServico");

                    b.HasIndex("IdPecaInsumo");

                    b.HasIndex("IdOrdemServico", "IdPecaInsumo")
                        .IsUnique();

                    b.ToTable("item_peca_insumo", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.ItemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime?>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<Guid>("IdOrdemServico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ordem_servico");

                    b.Property<Guid>("IdServico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_servico");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdemServico");

                    b.HasIndex("IdServico");

                    b.HasIndex("IdOrdemServico", "IdServico")
                        .IsUnique();

                    b.ToTable("item_servico", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdOrdemServico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ordem_servico");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdemServico")
                        .IsUnique();

                    b.ToTable("orcamento", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<Guid>("IdStatus")
                        .HasColumnType("uuid")
                        .HasColumnName("id_status");

                    b.Property<Guid>("IdVeiculo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_veiculo");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("ordem_servico", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.PecaInsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("peca_insumo", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("permissao", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int>("TempoEstimadoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("tempo_estimado_minutos");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.StatusOrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("status_ordem_servico", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdPermissao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_permissao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPermissao");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apagado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculo", (string)null);
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("Fiap.TechChallenge.Domain.Entities.PecaInsumo", "PecaInsumo")
                        .WithOne()
                        .HasForeignKey("Fiap.TechChallenge.Domain.Entities.Estoque", "IdPecaInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PecaInsumo");
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.ItemPecaInsumo", b =>
                {
                    b.HasOne("Fiap.TechChallenge.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("ItensPecaInsumo")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.TechChallenge.Domain.Entities.PecaInsumo", "PecaInsumo")
                        .WithMany()
                        .HasForeignKey("IdPecaInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("PecaInsumo");
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.ItemServico", b =>
                {
                    b.HasOne("Fiap.TechChallenge.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("ItensServico")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.TechChallenge.Domain.Entities.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Orcamento", b =>
                {
                    b.HasOne("Fiap.TechChallenge.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithOne("Orcamento")
                        .HasForeignKey("Fiap.TechChallenge.Domain.Entities.Orcamento", "IdOrdemServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("Fiap.TechChallenge.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.TechChallenge.Domain.Entities.StatusOrdemServico", "Status")
                        .WithMany()
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.TechChallenge.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Status");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Fiap.TechChallenge.Domain.Entities.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Fiap.TechChallenge.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("ItensPecaInsumo");

                    b.Navigation("ItensServico");

                    b.Navigation("Orcamento");
                });
#pragma warning restore 612, 618
        }
    }
}
